name: Build-Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install app dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build app and install deps for api
        run: npm run build

  test_app:
    runs-on: ubuntu-20.04
    needs:
      - build_job
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci && npm run build
      - name: App tests
        run: npm run test
      - name: Api tests
        run: npm run api:test
      # - name: Setup e2e:Install Playwright Browsers
      #   run: npx playwright install --with-deps
      # - name: Setup e2e:Spin api
      #   run: npm run dev:start:test
      # - name: Setup e2e:Spin app
      #   run: npm run dev
      # - name: App e2e tests
      #   run: npm run chromiumb
