name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install app dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build app and install deps for api
        run: npm run build
