name: Build-Test-Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install app dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build app and install deps for api
        run: npm run build

  test_job:
    runs-on: ubuntu-20.04
    needs: build_job
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci && npm run build
      - name: App tests
        run: npm run test
      - name: Api tests
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
        run: >
          export TEST_MONGODB_URI='${{secrets.TEST_MONGODB_URI}}' &&
          npm run api:test
      - name: Setup e2e:Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Setup e2e:Spin api
        run: >
          (export TEST_MONGODB_URI='${{secrets.TEST_MONGODB_URI}}' &&
          export SECRET=${{secrets.SECRET}} && 
          npm run dev & sleep 2) &&
          npm run chromium && killall -9 node

  deploy_job:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
    needs: test_job
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Render Deployment
        uses: sws2apps/render-deployment@v1.7.0
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false

  tag_release:
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    needs: [deploy_job]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: semver tag release
        id: tagRelease
        uses: anothrNick/github-tag-action@777684df761b882a3f4f70db16ac70d8cc78d0ea
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true
          DEFAULT_BUMP: "patch"
