name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: [completed]

jobs:
  test_app:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: App tests
        run: npm run test
      - name: Api tests
        run: npm run api:test
      # - name: Setup e2e:Install Playwright Browsers
      #   run: npx playwright install --with-deps
      # - name: Setup e2e:Spin api
      #   run: npm run dev:start:test
      # - name: Setup e2e:Spin app
      #   run: npm run dev
      # - name: App e2e tests
      #   run: npm run chromium
